import org.gradle.internal.os.OperatingSystem

plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '7.1.2'
    id 'org.openjfx.javafxplugin' version '0.0.10'
    id 'bo.firmadigital.jacobitus4.java-conventions'
}

group = 'bo.firmadigital.jacobitus4'
version = '1.4.0'
description = 'Jacobitus4'
mainClassName = 'bo.firmadigital.jacobitus4.Main'

def appName = 'Jacobitus Escritorio'
def jarName = "jacobitus-escritorio"

def os = OperatingSystem.current()

repositories {
    mavenLocal()
    mavenCentral()
    flatDir { dirs 'libs' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    implementation project(path: ':jacobitus-libreria', configuration: 'shadow')

    implementation 'org.openjfx:javafx-controls:15.0.1'
    implementation 'org.openjfx:javafx-fxml:15.0.1'
    implementation 'org.openjfx:javafx-swing:15.0.1'

    implementation 'org.eclipse.jetty:jetty-server:10.0.21'
    implementation 'org.eclipse.jetty:jetty-servlet:10.0.21'
    implementation 'org.eclipse.jetty:jetty-servlets:10.0.21'
    implementation 'org.glassfish.jersey.containers:jersey-container-jetty-servlet:2.43'
    implementation 'org.glassfish.jersey.inject:jersey-hk2:2.43'

    implementation 'org.bouncycastle:bcpkix-jdk15on:1.70'
    implementation 'com.itextpdf:sign:7.1.15'
    implementation 'com.nimbusds:nimbus-jose-jwt:9.1.2'
    implementation 'org.codehaus.jettison:jettison:1.5.1'
    implementation 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'
    implementation 'org.apache.santuario:xmlsec:2.3.1'

    implementation 'com.digitalpersona.onetouch:dpotapi:1.0'
    implementation 'com.digitalpersona.onetouch:dpotjni:1.0'
    implementation 'fr.opensagres.xdocreport:org.odftoolkit.odfdom.converter.pdf:1.0.6'
    implementation 'fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.pdf:1.0.6'

    implementation 'com.vdurmont:semver4j:3.1.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'junit:junit:4.13.2'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

javafx {
    version = '15.0.1'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.swing', 'javafx.base']
}

jar {
    archiveBaseName = jarName
    archiveVersion = version
    manifest {
        attributes 'Main-Class': mainClassName
    }
}

shadowJar {
    archiveBaseName = jarName
    archiveVersion = version
    archiveClassifier = ''
    mergeServiceFiles()
}

// tasks.withType(JavaCompile).configureEach {
//     options.encoding = 'UTF-8'
// }

// tasks.withType(Javadoc).configureEach {
//     options.encoding = 'UTF-8'
// }

// tasks.withType(JavaExec).configureEach {
//     jvmArgs += '-Dfile.encoding=UTF-8'
// }

tasks.register('importCA', Copy) {
    from 'ca'
    into 'build/libs/ca'
}

tasks.register('addDrivers', Copy) {
    group = 'build'

    def driversDir

    if (os.isLinux()) {
        driversDir = layout.projectDirectory.dir('controladores/linux')
    } else if (os.isMacOsX()) {
        driversDir = layout.projectDirectory.dir('controladores/macos')
    } else if (os.isWindows()) {
        driversDir = layout.projectDirectory.dir('controladores/windows')
    } else {
        throw new GradleException("Sistema operativo no soportado")
    }

    from driversDir
    into layout.buildDirectory.dir('libs/controladores')
}

tasks.register('importChangePin', Copy) {
    group = 'build'

    if (os.isLinux()) {
        from project(':jacobitus-libreria').file('build/libs/libchangepin.so')
    } else if (os.isMacOsX()) {
        from project(':jacobitus-libreria').file('build/libs/libchangepin.dylib')
    } else if (os.isWindows()) {
        from project(':jacobitus-libreria').file('build/libs/changepin.dll')
    }

    into 'build/libs'
}

def jpackageCmd = [
    "${System.getProperty("java.home")}/bin/jpackage",
    '--verbose',
    '--input', 'build/libs',
    '--main-class', mainClassName,
    '--main-jar', "${jarName}-${version}.jar",
    '--vendor', 'AGETIC',
    '--dest', 'dist',
    '--name', appName,
    '--app-version', version.replace('-1', ''),
    '--description', appName,
    '--file-associations', 'FAjws.properties',
    '--file-associations', 'FAp7s.properties',
    '--file-associations', 'FApdf.properties',
    '--java-options', '-Dfile.encoding=UTF-8',
    '--license-file', 'license.txt'
]

tasks.register('packageApp', Exec) {
    group = 'distribution'

    dependsOn clean
    dependsOn ':jacobitus-libreria:buildNative'
    dependsOn shadowJar
    dependsOn importCA
    dependsOn addDrivers
    dependsOn importChangePin

    def osArgs = []

    if (os.isLinux()) {
        osArgs = [
            '--type', 'deb',
            '--icon', 'iconos/icon.png',
            '--linux-package-name', 'jacobitus-escritorio',
            '--linux-deb-maintainer', 'desarrollo@firmadigital.bo',
            '--linux-package-deps', 'libnss3-tools, pcscd, pcsc-tools, libnss3, libpcsclite1',
            '--linux-shortcut'
        ]
    } else if (os.isMacOsX()) {
        osArgs = [
            '--type', 'dmg',
            '--icon', 'iconos/icon.icns'
        ]
    } else if (os.isWindows()) {
        osArgs = [
            '--type', 'msi',
            '--icon', 'iconos/icon.ico',
            '--win-shortcut',
            '--win-menu',
            '--win-menu-group', 'AGETIC',
            '--win-upgrade-uuid', "47fdae43-82ca-40ca-887f-8e6459366643"
        ]
    } else {
        throw new GradleException("Sistema operativo no soportado")
    }

    project(':jacobitus-libreria').tasks.findByName('buildNative').mustRunAfter 'clean'
    tasks.findByName('importCA').mustRunAfter 'clean'
    tasks.findByName('addDrivers').mustRunAfter 'clean', ':jacobitus-libreria:buildNative'
    tasks.findByName('importChangePin').mustRunAfter 'clean', ':jacobitus-libreria:buildNative'
    tasks.findByName('shadowJar').mustRunAfter ':jacobitus-libreria:buildNative', 'importChangePin', 'importCA'

    commandLine(jpackageCmd + osArgs)
}
