import org.gradle.internal.os.OperatingSystem

plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.10'
    id 'bo.firmadigital.jacobitus4.java-conventions'
}

group = 'bo.firmadigital.jacobitus4'
version = '1.4.0'
mainClassName = 'bo.firmadigital.jacobitus4.Main'

def appName = 'Jacobitus Escritorio'
def appDescription = 'Solución completa para la administración de tu dispositivo criptográfico y firma digital'
def jarName = "jacobitus-escritorio"
def vendorName = 'AGETIC'
def maintainer = 'desarrollo@firmadigital.bo'

def os = OperatingSystem.current()
def arch = System.getProperty("os.arch").toLowerCase()
def is64Bits = arch.contains("64")

repositories {
    mavenLocal()
    mavenCentral()
    flatDir { dirs 'libs' }
}

dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')
    implementation project(':jacobitus-libreria')

    implementation 'org.openjfx:javafx-controls:15.0.1'
    implementation 'org.openjfx:javafx-fxml:15.0.1'
    implementation 'org.openjfx:javafx-swing:15.0.1'

    implementation 'org.eclipse.jetty:jetty-server:10.0.21'
    implementation 'org.eclipse.jetty:jetty-servlet:10.0.21'
    implementation 'org.eclipse.jetty:jetty-servlets:10.0.21'
    implementation 'org.glassfish.jersey.containers:jersey-container-jetty-servlet:2.43'
    implementation 'org.glassfish.jersey.inject:jersey-hk2:2.43'

    implementation 'org.bouncycastle:bcpkix-jdk18on:1.78'
    implementation 'com.itextpdf:sign:7.2.6'
    implementation 'com.nimbusds:nimbus-jose-jwt:9.1.2'
    implementation 'org.codehaus.jettison:jettison:1.5.1'
    implementation 'org.codehaus.jackson:jackson-mapper-asl:1.9.13'
    implementation 'org.apache.santuario:xmlsec:2.3.1'

    implementation 'com.digitalpersona.onetouch:dpotapi:1.0'
    implementation 'com.digitalpersona.onetouch:dpotjni:1.0'
    implementation 'fr.opensagres.xdocreport:org.odftoolkit.odfdom.converter.pdf:1.0.6'
    implementation 'fr.opensagres.xdocreport:org.apache.poi.xwpf.converter.pdf:1.0.6'

    implementation 'com.vdurmont:semver4j:3.1.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'junit:junit:4.13.2'
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

javafx {
    version = '15.0.1'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.graphics', 'javafx.swing', 'javafx.base']
}

jar {
    archiveBaseName = jarName
    archiveVersion = version
    manifest {
        attributes(
            'Main-Class': mainClassName,
            'Class-Path': configurations.runtimeClasspath.files.collect { file ->
                if (file.name.contains("jacobitus-libreria")) {
                    return file.name
                }
                return "dependencias/${file.name}"
            }.join(' ')
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(JavaExec).configureEach {
    jvmArgs += '-Dfile.encoding=UTF-8'
}

tasks.register('importCA', Copy) {
    from 'ca'
    into 'build/libs/ca'
}

tasks.register('addDrivers', Copy) {
    group = 'build'

    def driversDir

    if (os.isLinux()) {
        driversDir = layout.projectDirectory.dir('controladores/linux')
    } else if (os.isMacOsX()) {
        driversDir = layout.projectDirectory.dir('controladores/macos')
    } else if (os.isWindows()) {
        driversDir = layout.projectDirectory.dir('controladores/windows')
    } else {
        throw new GradleException("Sistema operativo no soportado")
    }

    from driversDir
    into layout.buildDirectory.dir('libs/controladores')
}

tasks.register('importChangePin', Copy) {
    group = 'build'

    if (os.isLinux()) {
        from project(':jacobitus-libreria').file('build/libs/libchangepin.so')
    } else if (os.isMacOsX()) {
        from project(':jacobitus-libreria').file('build/libs/libchangepin.dylib')
    } else if (os.isWindows()) {
        from project(':jacobitus-libreria').file('build/libs/changepin.dll')
    }

    into 'build/libs'
}

def jpackageCmd = [
    "${System.getProperty("java.home")}/bin/jpackage",
    '--verbose',
    '--input', 'build/libs',
    '--main-class', mainClassName,
    '--main-jar', "${jarName}-${version.replace('-1', '')}.jar",
    '--vendor', vendorName,
    '--dest', 'dist',
    '--name', appName,
    '--app-version', version.replace('-1', ''),
    '--description', appDescription,
    '--file-associations', 'FAjws.properties',
    '--file-associations', 'FAp7s.properties',
    '--file-associations', 'FApdf.properties',
    '--java-options', '-Dfile.encoding=UTF-8',
    '--license-file', 'license.txt'
]

tasks.register('copyAllDependencies') {
    group = 'build'

    dependsOn configurations.runtimeClasspath
    dependsOn ':jacobitus-libreria:jar'

    doLast {
        copy {
            from configurations.runtimeClasspath
            from project(':jacobitus-libreria').file("build/dependencies")
            into layout.buildDirectory.dir('libs/dependencias')
            
            exclude { element -> element.file.name.contains("jacobitus-libreria") }
            exclude '*.so', '*.dylib', '*.dll'
            
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }

        copy {
            from project(':jacobitus-libreria').layout.buildDirectory.dir('libs')
            into layout.buildDirectory.dir('libs')
            include '*.jar'
            exclude '*.so', '*.dylib', '*.dll'
            
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }
    }
}

tasks.register('packageApp', Exec) {

    group = 'distribution'

    dependsOn clean
    dependsOn ':jacobitus-libreria:buildNative'
    dependsOn jar
    dependsOn copyAllDependencies
    dependsOn importCA
    dependsOn addDrivers
    dependsOn importChangePin

    def osArgs = []

    if (os.isLinux()) {
        osArgs = [
            '--type', 'deb',
            '--icon', 'iconos/icon.png',
            '--resource-dir', 'plantillas/deb',
            '--linux-package-name', jarName,
            '--linux-deb-maintainer', maintainer,
            '--linux-package-deps', 'libnss3-tools, pcscd, pcsc-tools, libnss3, libpcsclite1',
            '--linux-shortcut'
        ]
    } else if (os.isMacOsX()) {
        osArgs = [
            '--type', 'pkg',
            '--icon', 'iconos/icon.icns'
        ]
    } else if (os.isWindows()) {
        if (is64Bits) {
            println "Generando instalador Windows MSI 64 bits"
            osArgs = [
                '--type', 'msi',
                '--icon', 'iconos/icon.ico',
                '--resource-dir', 'plantillas/windows',
                '--win-shortcut',
                '--win-menu',
                '--win-menu-group', 'AGETIC',
                '--win-upgrade-uuid', "47fdae43-82ca-40ca-887f-8e6459366643"
            ]
        } else {
            println "Generando instalador Windows MSI 32 bits"
            osArgs = [
                '--type', 'msi',
                '--icon', 'iconos/icon.ico',
                '--resource-dir', 'plantillas/windows',
                '--win-shortcut',
                '--win-menu',
                '--win-menu-group', 'AGETIC',
                '--win-upgrade-uuid', "47fdae43-82ca-40ca-887f-8e6459366643"
            ]
        }
    } else {
        throw new GradleException("Sistema operativo no soportado")
    }

    project(':jacobitus-libreria').tasks.findByName('buildNative').mustRunAfter 'clean'
    tasks.findByName('jar').mustRunAfter ':jacobitus-libreria:buildNative'
    tasks.findByName('copyAllDependencies').mustRunAfter 'jar'
    tasks.findByName('importCA').mustRunAfter('clean')
    tasks.findByName('addDrivers').mustRunAfter('clean', ':jacobitus-libreria:buildNative')
    tasks.findByName('importChangePin').mustRunAfter('clean', ':jacobitus-libreria:buildNative')

    commandLine(jpackageCmd + osArgs)
}

tasks.register('packageRpm') {

    group = 'distribution'

    def appCategory = 'Utility;'
    def mimeTypes = 'application/jose;application/pkcs7-signature;application/pdf'

    def rpmRoot = file("${buildDir}/rpm")
    def tempAppImageDir = file("${buildDir}/tmp/app-image")
    def appImageDir = file("${tempAppImageDir}/${appName}")
    def specTemplate = file("${projectDir}/plantillas/rpm/${jarName}.spec")
    def desktopTemplate = file("${projectDir}/plantillas/rpm/resources/${jarName}-${appName.replace(' ', '')}.desktop")

    dependsOn clean
    dependsOn ':jacobitus-libreria:buildNative'
    dependsOn jar
    dependsOn copyAllDependencies
    dependsOn importCA
    dependsOn addDrivers
    dependsOn importChangePin

    project(':jacobitus-libreria').tasks.findByName('buildNative').mustRunAfter 'clean'
    tasks.findByName('jar').mustRunAfter ':jacobitus-libreria:buildNative'
    tasks.findByName('copyAllDependencies').mustRunAfter 'jar'
    tasks.findByName('importCA').mustRunAfter('clean')
    tasks.findByName('addDrivers').mustRunAfter('clean', ':jacobitus-libreria:buildNative')
    tasks.findByName('importChangePin').mustRunAfter('clean', ':jacobitus-libreria:buildNative')

    doFirst {
        if (tempAppImageDir.exists()) {
            logger.lifecycle("Eliminando app-image previo...")
            delete tempAppImageDir
        }

        tempAppImageDir.mkdirs()

        delete rpmRoot

        ['BUILD', 'RPMS', 'SOURCES', 'SPECS', 'SRPMS'].each {
            file("${rpmRoot}/${it}").mkdirs()
        }
    }

    doLast {
        exec {
            workingDir './'
            commandLine([
                    "${System.getProperty("java.home")}/bin/jpackage",
                    '--verbose',
                    '--input', 'build/libs',
                    '--main-class', mainClassName,
                    '--main-jar', "${jarName}-${version.replace('-1', '')}.jar",
                    '--vendor', vendorName,
                    '--dest', tempAppImageDir.absolutePath,
                    '--name', appName,
                    '--app-version', version.replace('-1', ''),
                    '--description', appDescription,
                    '--java-options', '-Dfile.encoding=UTF-8',

                    '--type', 'app-image',
                    '--icon', './iconos/icon.png',
            ])
        }

        appImageDir = tempAppImageDir.listFiles()?.find {
            it.isDirectory()
        }

        if (appImageDir == null || !appImageDir.exists()) {
            throw new GradleException("No se encontró el app-image en ${tempAppImageDir}")
        }

        def sourceDir = file("${rpmRoot}/SOURCES/opt/${jarName}")

        copy {
            from appImageDir
            into sourceDir
        }

        copy {
            from(appImageDir) {
                include '**/*.png'
                eachFile { file ->
                    if (file.name.contains(' ')) {
                        file.name = file.name.replaceAll(/\s+/, '_')
                    }
                }
                includeEmptyDirs = false
            }
            into sourceDir
        }

        def desktopFile = file("${sourceDir}/lib/${jarName}-${appName.replace(' ', '')}.desktop")

        def desktopContent = desktopTemplate.text
                .replace('@APP_NAME@', appName)
                .replace('@DESCRIPTION@', appDescription)
                .replace('@INSTALL_DIR@', "/opt/${jarName}")
                .replace('@EXECUTABLE_NAME@', appName)
                .replace('@ICON_NAME@', "${appName.replace(' ', '_')}.png")
                .replace('@CATEGORY@', appCategory)
                .replace('@MIME_TYPES@', mimeTypes)

        desktopFile.text = desktopContent

        logger.lifecycle("Desktop file generado: ${desktopFile.absolutePath}")

        copy {
            from ("${projectDir}/plantillas/rpm/resources") {
                exclude '*.desktop'
            }
            into "${sourceDir}/lib"
        }

        def specFile = file("${rpmRoot}/SPECS/${jarName}.spec")

        def specContent = specTemplate.text
                .replace('@SUMMARY@', appName)
                .replace('@NAME@', jarName)
                .replace('@VERSION@', version)
                .replace('@RELEASE@', '1')
                .replace('@LICENSE@', 'LPG-Bolivia')
                .replace('@VENDOR@', vendorName)
                .replace('@PREFIX@', '/opt')
                .replace('@PROVIDES@', jarName)
                .replace('@GROUP@', 'Utility')
                .replace('@REQUIRES@', ', nss-tools, pcsc-lite, pcsc-lite-ccid, pcsc-tools, nss, pcsc-lite-libs')
                .replace('@DESCRIPTION@', appDescription)
                .replace('@SOURCE_DIR@', "/opt/${jarName}")
                .replace('@INSTALL_DIR@', "/opt/${jarName}")
                .replace('@LICENSE_FILE@', "${projectDir}/license.txt")
                .replace('@DESKTOP_FILE@', "/opt/${jarName}/lib/${jarName}-${appName.replace(' ', '')}.desktop")
                .replace('@MIME_FILE@', "/opt/${jarName}/lib/${jarName}-${appName.replace(' ', '')}-MimeInfo.xml")
                .replace('@UNINSTALL_MIME@', "${jarName}-${appName.replace(' ', '')}.desktop application/jose application/pkcs7-signature application/pdf")

        specFile.text = specContent

        logger.lifecycle("SPEC generado: ${specFile.absolutePath}")

        exec {
            environment 'HOME', rpmRoot.absolutePath
            commandLine('rpmbuild', '--define', "_topdir ${rpmRoot.absolutePath}", '-bb', specFile.absolutePath)
        }

        def rpmFiles = fileTree("${rpmRoot}/RPMS").matching {
            include '**/*.rpm'
        }.files

        if (rpmFiles.empty) {
            throw new GradleException("No se generó el RPM")
        }

        def rpmOutput = rpmFiles.first()

        copy {
            from rpmOutput
            into "${projectDir}/dist"
        }

        logger.lifecycle("RPM generado: ${rpmOutput.name}")
    }
}

tasks.register('packageArch') {
    group = 'distribution'

    def appCategory = 'Utility'
    def mimeTypes = 'application/jose;application/pkcs7-signature;application/pdf'

    def archRoot = file("${buildDir}/arch")
    def tempAppImageDir = file("${buildDir}/tmp/app-image")

    dependsOn clean
    dependsOn ':jacobitus-libreria:buildNative'
    dependsOn jar
    dependsOn copyAllDependencies
    dependsOn importCA
    dependsOn addDrivers
    dependsOn importChangePin

    project(':jacobitus-libreria').tasks.findByName('buildNative').mustRunAfter 'clean'
    tasks.findByName('jar').mustRunAfter ':jacobitus-libreria:buildNative'
    tasks.findByName('copyAllDependencies').mustRunAfter 'jar'
    tasks.findByName('importCA').mustRunAfter('clean')
    tasks.findByName('addDrivers').mustRunAfter('clean', ':jacobitus-libreria:buildNative')
    tasks.findByName('importChangePin').mustRunAfter('clean', ':jacobitus-libreria:buildNative')

    doFirst {
        if (tempAppImageDir.exists()) {
            logger.lifecycle("Eliminando app-image previo...")
            delete tempAppImageDir
        }
        delete archRoot

        tempAppImageDir.mkdirs()
        archRoot.mkdirs()
    }

    doLast {
        exec {
            workingDir './'
            commandLine([
                    "${System.getProperty("java.home")}/bin/jpackage",
                    '--verbose',
                    '--input', 'build/libs',
                    '--main-class', mainClassName,
                    '--main-jar', "${jarName}-${version.replace('-1', '')}.jar",
                    '--vendor', vendorName,
                    '--dest', tempAppImageDir.absolutePath,
                    '--name', appName,
                    '--app-version', version.replace('-1', ''),
                    '--description', appDescription,
                    '--java-options', '-Dfile.encoding=UTF-8',
                    '--type', 'app-image',
                    '--icon', './iconos/icon.png',
            ])
        }

        def appImageDir = tempAppImageDir.listFiles()?.find { it.isDirectory() }

        if (appImageDir == null || !appImageDir.exists()) {
            throw new GradleException("No se encontró el app-image generado por jpackage")
        }

        def packageDir = file("${archRoot}/${jarName}")

        copy {
            from appImageDir
            into "${packageDir}/opt/${jarName}"
        }

        copy {
            from(appImageDir) {
                include '**/*.png'
                eachFile { file ->
                    if (file.name.contains(' ')) {
                        file.name = file.name.replaceAll(/\s+/, '_')
                    }
                }
                includeEmptyDirs = false
            }
            into "${packageDir}/opt/${jarName}"
        }

        copy {
            from("${projectDir}/plantillas/arch/resources") {
                exclude '*.desktop'
            }
            into "${packageDir}/opt/${jarName}/lib"
        }

        def installTemplate = file("${projectDir}/plantillas/arch/resources/${jarName}-${appName.replace(' ', '')}.install")
        def installFile = file("${archRoot}/${jarName.toLowerCase()}.install")

        if (installTemplate.exists()) {
            def installContent = installTemplate.text
                    .replace('@APP_NAME@', appName)
            
            installFile.text = installContent
            logger.lifecycle(".install file generado: ${installFile.absolutePath}")
        } else {
            throw new GradleException("No se encontró la plantilla app.install en ${installTemplate.absolutePath}")
        }

        def desktopTemplate = file("${projectDir}/plantillas/arch/resources/${jarName}-${appName.replace(' ', '')}.desktop")
        def desktopFile = file("${packageDir}/opt/${jarName}/lib/${jarName}-${appName.replace(' ', '')}.desktop")

        if (desktopTemplate.exists()) {
            def desktopContent = desktopTemplate.text
                    .replace('@APP_NAME@', appName)
                    .replace('@DESCRIPTION@', appDescription)
                    .replace('@INSTALL_DIR@', "/opt/${jarName}")
                    .replace('@EXECUTABLE_NAME@', appName)
                    .replace('@ICON_NAME@', "${appName.replace(' ', '_')}.png")
                    .replace('@CATEGORY@', appCategory)
                    .replace('@MIME_TYPES@', mimeTypes)
            desktopFile.text = desktopContent
            logger.lifecycle("Desktop file generado: ${desktopFile.absolutePath}")
        }

        def mimeSource = file("${projectDir}/plantillas/arch/${jarName}.xml")
        if (mimeSource.exists()) {
            copy {
                from mimeSource
                into archRoot
            }
        } else {
            file("${archRoot}/${jarName}.xml").text = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<mime-info xmlns=\"http://www.freedesktop.org/standards/shared-mime-info\"></mime-info>"
        }

        def pkgbuildTemplate = file("${projectDir}/plantillas/arch/PKGBUILD")
        def pkgbuildFile = file("${archRoot}/PKGBUILD")
        def ARCH_DEPENDS = "'nss' 'pcsclite' 'ccid' 'pcsc-tools'"
        def ARCH_OPTDEPENDS = ""        
        
        def pkgbuildContent = pkgbuildTemplate.text
                .replace('@PKGNAME@', jarName.toLowerCase())
                .replace('@PKGVER@', version.replace('-1', ''))
                .replace('@PKGREL@', '1')
                .replace('@PKGDESC@', appDescription)
                .replace('@ARCH@', 'x86_64')
                .replace('@URL@', 'https://firmadigital.bo/herramientas/jacobitus-escritorio')
                .replace('@LICENSE@', 'LPG-Bolivia')
                .replace("@REQUIRES@", ARCH_DEPENDS)
                .replace("@OPTREQUIRES@", ARCH_OPTDEPENDS)
                .replace('@VENDOR@', vendorName)
                .replace('@APP_NAME@', appName.replace(' ', ''))
                .replace('@JAR_NAME@', jarName)

        pkgbuildFile.text = pkgbuildContent
        logger.lifecycle("PKGBUILD generado: ${pkgbuildFile.absolutePath}")

        exec {
            workingDir archRoot
            commandLine 'makepkg', '-f', '--nodeps', '--noextract'
        }

        def pkgFiles = fileTree(archRoot).matching {
            include "${jarName}-*.pkg.tar.zst"
            exclude '*-debug-*.pkg.tar.zst'
        }.files

        if (pkgFiles.empty) {
            throw new GradleException("No se generó el paquete ArchLinux (.pkg.tar.zst)")
        }

        def pkgOutput = pkgFiles.first()

        copy {
            from pkgOutput
            into "${projectDir}/dist"
        }

        logger.lifecycle("Paquete Arch compilado con éxito: ${pkgOutput.name} en dist/")
    }
}
